import fs from 'fs'
import path from 'path'
import {
  BOOKMARK_CATEGORIES,
  CHANNEL_CATEGORIES,
} from '../features/bookmarks/constants/categories'
import { PREVIEWABLE_HOSTS } from '../features/bookmarks/constants/previewable'
import type { Bookmark } from '../features/bookmarks/types'

/**
 * Guards content/bookmarks.json.
 *
 * The catalogue is now mostly generated by scripts/import-designeer.mjs, so the
 * invariants that keep the page rendering correctly are asserted here rather
 * than trusted to a scraper run nobody re-runs by hand.
 */

const FILE_PATH = path.join(process.cwd(), 'content', 'bookmarks.json')

function loadBookmarks(): Bookmark[] {
  return JSON.parse(fs.readFileSync(FILE_PATH, 'utf-8')) as Bookmark[]
}

const bookmarks = loadBookmarks()

describe('content/bookmarks.json', () => {
  it('is a non-empty array', () => {
    expect(Array.isArray(bookmarks)).toBe(true)
    expect(bookmarks.length).toBeGreaterThan(0)
  })

  it('gives every row the fields the row components read', () => {
    for (const bookmark of bookmarks) {
      expect(typeof bookmark.id).toBe('string')
      expect(bookmark.id.length).toBeGreaterThan(0)
      expect(typeof bookmark.title).toBe('string')
      expect(bookmark.title.length).toBeGreaterThan(0)
      expect(typeof bookmark.url).toBe('string')
      expect(bookmark.url).toMatch(/^https?:\/\//)
      expect(typeof bookmark.description).toBe('string')
      expect(Array.isArray(bookmark.tags)).toBe(true)
      expect(typeof bookmark.createdAt).toBe('string')
    }
  })

  it('keeps ids unique', () => {
    const ids = bookmarks.map((bookmark) => bookmark.id)
    expect(new Set(ids).size).toBe(ids.length)
  })

  it('keeps urls unique, ignoring a trailing slash', () => {
    const urls = bookmarks.map((bookmark) => bookmark.url.replace(/\/$/, ''))
    expect(new Set(urls).size).toBe(urls.length)
  })

  it('puts every row in a known channel', () => {
    const known = new Set<string>(CHANNEL_CATEGORIES)
    for (const bookmark of bookmarks) {
      expect(known.has(bookmark.category)).toBe(true)
    }
  })

  it('gives every channel in the data an LED colour', () => {
    const known = new Set<string>(BOOKMARK_CATEGORIES)
    for (const category of new Set(bookmarks.map((b) => b.category))) {
      expect(known.has(category)).toBe(true)
    }
  })

  it('preserves the hand-written bookmarks across an import', () => {
    const legacy = bookmarks.filter(
      (bookmark) => !bookmark.id.startsWith('bm-des-'),
    )
    expect(legacy.length).toBeGreaterThan(0)
  })

  it('carries the designeer import', () => {
    const imported = bookmarks.filter((bookmark) =>
      bookmark.id.startsWith('bm-des-'),
    )
    expect(imported.length).toBeGreaterThan(500)
    for (const bookmark of imported) {
      expect(bookmark.tags).toContain('designeer')
    }
  })

  it('pins exactly twelve links', () => {
    expect(bookmarks.filter((b) => b.featured)).toHaveLength(12)
  })

  it('pins the curated set, matched by url the way the importer does', () => {
    const pinned = new Set(
      bookmarks.filter((b) => b.featured).map((b) => b.url.replace(/\/$/, '')),
    )
    // Kept in sync with PINNED_URLS in scripts/import-designeer.mjs. The set is
    // a curation and not a scrape, so it is asserted here rather than trusted
    // to whatever the last import happened to write.
    for (const url of [
      'https://reactbits.dev',
      'https://ui.shadcn.com',
      'https://magicui.design',
      'https://ui.aceternity.com',
      'https://motion.dev',
      'https://gsap.com',
      'https://beui.dev',
      'https://21st.dev',
      'https://lucide.dev',
      'https://www.awwwards.com',
      'https://emilkowal.ski',
      'https://shoogle.dev',
    ]) {
      expect(pinned.has(url)).toBe(true)
    }
  })

  it('does not pin the links swapped out of the crate', () => {
    const pinned = bookmarks.filter((b) => b.featured).map((b) => b.url)
    for (const url of [
      'https://huggingface.co',
      'https://nextjs.org',
      'https://tonejs.github.io',
      'https://joshwcomeau.com',
      'https://r3f.docs.pmnd.rs',
      'https://threejs.org',
    ]) {
      expect(pinned).not.toContain(url)
    }
  })
})

describe('PREVIEWABLE_HOSTS', () => {
  it('excludes every host that refused framing', () => {
    // Each of these answers with X-Frame-Options or a frame-ancestors policy
    // that excludes us, so a frame would render blank with no error to catch.
    for (const host of [
      'designeer.xyz',
      'awwwards.com',
      'oklch.com',
      'gsap.com',
      'screen.studio',
      'raphaelsalaja.com',
    ]) {
      expect(PREVIEWABLE_HOSTS.has(host)).toBe(false)
    }
  })

  it('includes hosts known to allow framing', () => {
    expect(PREVIEWABLE_HOSTS.has('reactbits.dev')).toBe(true)
    expect(PREVIEWABLE_HOSTS.has('threejs.org')).toBe(true)
  })

  it('matches a bookmark url only by its bare hostname', () => {
    for (const host of PREVIEWABLE_HOSTS) {
      expect(host).not.toMatch(/^(www\.|https?:)/)
    }
  })
})
